services:
  loki:
    image: grafana/loki:${LOKI_VERSION}
    depends_on:
      s3:
        condition: service_healthy
      s3-loki-bucket:
        condition: service_completed_successfully
    ports:
      - 3100:3100
    volumes:
      - ./config.yaml:/etc/loki/config.yaml
    command:
      - --config.file=/etc/loki/config.yaml
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://localhost:3100/ready"]
      timeout: 45s
      interval: 30s
      start_period: 40s
      retries: 3
  s3:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 1s
    restart: always
  s3-loki-bucket:
    image: minio/mc
    depends_on:
      s3:
        condition: service_healthy
    network_mode: service:s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set loki http://minio:9000 minio_access_key minio_secret_key;
      /usr/bin/mc rm -r --force loki/loki || true;
      /usr/bin/mc mb --ignore-existing loki/loki;
      /usr/bin/mc anonymous set download loki/loki;
      exit 0;
      "